package formatter

import (
	"bufio"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

type LLMSTxtFormatter struct {
	projectName string
	summary     string
}

func NewLLMSTxt() *LLMSTxtFormatter {
	f := &LLMSTxtFormatter{
		projectName: "Project",
		summary:     "Project codebase packed for LLMs.",
	}
	f.detectProjectInfo()
	return f
}

func (f *LLMSTxtFormatter) detectProjectInfo() {
	cwd, err := os.Getwd()
	if err == nil {
		f.projectName = filepath.Base(cwd)
	}

	// Try to get info from README.md
	readmePath := "README.md"
	if _, err := os.Stat(readmePath); err == nil {
		file, err := os.Open(readmePath)
		if err == nil {
			defer file.Close()
			scanner := bufio.NewScanner(file)
			foundH1 := false
			foundSummary := false
			for scanner.Scan() {
				line := strings.TrimSpace(scanner.Text())
				if line == "" {
					continue
				}
				if !foundH1 && strings.HasPrefix(line, "# ") {
					f.projectName = strings.TrimPrefix(line, "# ")
					foundH1 = true
					continue
				}
				if foundH1 && !foundSummary && !strings.HasPrefix(line, "#") {
					f.summary = line
					foundSummary = true
				}
				if foundH1 && foundSummary {
					break
				}
			}
		}
	}
}

func (f *LLMSTxtFormatter) Name() string { return "llms-txt" }

func (f *LLMSTxtFormatter) Start(w io.Writer) error {
	_, err := fmt.Fprintf(w, "# %s\n\n> %s\n\n", f.projectName, f.summary)
	return err
}

func (f *LLMSTxtFormatter) WriteTree(w io.Writer, tree string) error {
	_, err := fmt.Fprintf(w, "## File Tree\n\n```text\n%s\n```\n\n## Files\n\n", tree)
	return err
}

func (f *LLMSTxtFormatter) AddFile(w io.Writer, relPath string, content []byte) error {
	// For llms.txt, we usually just list the files if it's the index.
	_, err := fmt.Fprintf(w, "- [%s](%s)\n", relPath, relPath)
	return err
}

func (f *LLMSTxtFormatter) Close(w io.Writer) error {
	_, err := io.WriteString(w, "\n\n---\nGenerated by llmpack")
	return err
}
