package formatter

import (
	"bytes"
	"strings"
	"testing"
)

func TestLLMSTxtFormatter(t *testing.T) {
	f := NewLLMSTxt()
	var buf bytes.Buffer

	// Test Start
	if err := f.Start(&buf); err != nil {
		t.Fatalf("Start failed: %v", err)
	}
	output := buf.String()
	if !strings.HasPrefix(output, "# ") {
		t.Errorf("Expected H1 header, got: %s", output)
	}
	if !strings.Contains(output, "> ") {
		t.Errorf("Expected blockquote, got: %s", output)
	}

	// Test WriteTree
	buf.Reset()
	if err := f.WriteTree(&buf, "file1\nfile2"); err != nil {
		t.Fatalf("WriteTree failed: %v", err)
	}
	output = buf.String()
	if !strings.Contains(output, "## File Tree") {
		t.Errorf("Expected File Tree header, got: %s", output)
	}
	if !strings.Contains(output, "file1\nfile2") {
		t.Errorf("Expected file list in tree, got: %s", output)
	}

	// Test AddFile
	buf.Reset()
	if err := f.AddFile(&buf, "test.go", []byte("package main")); err != nil {
		t.Fatalf("AddFile failed: %v", err)
	}
	output = buf.String()
	if output != "- [test.go](test.go)\n" {
		t.Errorf("Expected markdown link, got: %s", output)
	}

	// Test Close
	buf.Reset()
	if err := f.Close(&buf); err != nil {
		t.Fatalf("Close failed: %v", err)
	}
	output = buf.String()
	if !strings.Contains(output, "Generated by llmpack") {
		t.Errorf("Expected footer, got: %s", output)
	}
}
