package formatter

import (
	"fmt"
	"io"
	"path/filepath"
	"strings"
)

type MarkdownFormatter struct{}

func NewMarkdown() *MarkdownFormatter { return &MarkdownFormatter{} }

func (f *MarkdownFormatter) Name() string { return "markdown" }

func (f *MarkdownFormatter) Start(w io.Writer) error {
	_, err := io.WriteString(w, "# Project Context\n\n")
	return err
}

func (f *MarkdownFormatter) WriteTree(w io.Writer, tree string) error {
	_, err := fmt.Fprintf(w, "## File Tree\n```text\n%s\n```\n\n", tree)
	return err
}

func (f *MarkdownFormatter) AddFile(w io.Writer, relPath string, content []byte) error {
	ext := strings.TrimPrefix(filepath.Ext(relPath), ".")
	if ext == "" {
		ext = "text"
	}

	header := fmt.Sprintf("## File: `%s`\n```%s\n", relPath, ext)
	footer := "\n```\n\n"

	if _, err := io.WriteString(w, header); err != nil {
		return err
	}
	if _, err := w.Write(content); err != nil {
		return err
	}
	if _, err := io.WriteString(w, footer); err != nil {
		return err
	}

	return nil
}

func (f *MarkdownFormatter) Close(w io.Writer) error {
	_, err := io.WriteString(w, "---\nGenerated by llmpack")
	return err
}
